using TS.NET.Photino;
using TS.NET.Sequencer;

namespace TS.NET.Sequences;

public class BenchCalibrationSequence : Sequence
{
    public BenchCalibrationVariables Variables { get; private set; }

    public BenchCalibrationSequence(Func<Dialog, DialogResult> uiDialog, BenchCalibrationVariables variables)
    {
        Name = "Bench calibration";
        Variables = variables;
        AddSteps(uiDialog);
        SetStepIndices();
    }

    private void AddSteps(Func<Dialog, DialogResult> uiDialog)
    {
        Steps =
        [
            new DialogStep("Cable check", uiDialog){ Title = "Cable check", Text = "Cables connected from 2x signal generators to channels 1-4?", Buttons = DialogButtons.YesNo, Icon = DialogIcon.Question },
            new InitialiseDeviceStep("Initialise device", Variables),
            new InitialiseSigGensStep("Initialise instruments", Variables),
            new LoadUserCalFromDeviceFallbackToFileStep("Load calibration from device/file", Variables),
            new WarmupStep("Warmup device", Variables) { Skip = false, AllowSkip = true },

            new AdcBranchGainsStep("Channel 1 - ADC branch gains - 100 MSPS", 0, 100_000_000, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AdcBranchGainsStep("Channel 1 - ADC branch gains - 165 MSPS", 0, 165_000_000, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AdcBranchGainsStep("Channel 1 - ADC branch gains - 250 MSPS", 0, 250_000_000, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AdcBranchGainsStep("Channel 1 - ADC branch gains - 330 MSPS", 0, 330_000_000, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AdcBranchGainsStep("Channel 1 - ADC branch gains - 500 MSPS", 0, 500_000_000, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AdcBranchGainsStep("Channel 1 - ADC branch gains - 660 MSPS", 0, 660_000_000, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AdcBranchGainsStep("Channel 1 - ADC branch gains - 1 GSPS", 0, 1_000_000_000, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new Step("Disconnect signal generator"){ Action = (CancellationToken cancellationToken) => { SigGens.Instance.SetSdgChannel([]); return Sequencer.Status.Done; }},

            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L0", 0, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L1", 0, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L2", 0, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L3", 0, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L4", 0, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L5", 0, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L6", 0, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L7", 0, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L8", 0, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L9", 0, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L10", 0, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L0", 0, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L1", 0, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L2", 0, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L3", 0, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L4", 0, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L5", 0, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L6", 0, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L7", 0, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L8", 0, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L9", 0, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L10", 0, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L0", 0, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L1", 0, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L2", 0, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L3", 0, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L4", 0, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L5", 0, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L6", 0, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L7", 0, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L8", 0, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L9", 0, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L10", 0, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L0", 0, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L1", 0, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L2", 0, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L3", 0, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L4", 0, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L5", 0, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L6", 0, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L7", 0, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L8", 0, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L9", 0, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L10", 0, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new FindSigGenZeroStep("Channel 1 - Signal generator zero", 0, Variables),

            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L0", 0, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L1", 0, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L2", 0, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L3", 0, PgaPreampGain.High, pgaLadder: 3, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L4", 0, PgaPreampGain.High, pgaLadder: 4, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L5", 0, PgaPreampGain.High, pgaLadder: 5, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L6", 0, PgaPreampGain.High, pgaLadder: 6, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L7", 0, PgaPreampGain.High, pgaLadder: 7, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L8", 0, PgaPreampGain.High, pgaLadder: 8, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L9", 0, PgaPreampGain.High, pgaLadder: 9, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - HG L10", 0, PgaPreampGain.High, pgaLadder: 10, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L0", 0, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L1", 0, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L2", 0, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L3", 0, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L4", 0, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L5", 0, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L6", 0, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L7", 0, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L8", 0, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L9", 0, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new BufferInputVppStep("Channel 1 - Buffer input Vpp - LG L10", 0, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AttenuatorStep("Channel 1 - Attenuator scale", 0, Variables),

            new PgaLoadSetupStep("Channel 1 - Setup PGA loading scale", 0, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 660 MSPS, 1 channel", 0, [0], 660_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 500 MSPS, 1 channel", 0, [0], 500_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 330 MSPS, 1 channel", 0, [0], 330_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 250 MSPS, 1 channel", 0, [0], 250_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 165 MSPS, 1 channel", 0, [0], 165_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 100 MSPS, 1 channel", 0, [0], 100_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 500 MSPS, 2 channel", 0, [0, 1], 500_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 330 MSPS, 2 channel", 0, [0, 1], 330_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 250 MSPS, 2 channel", 0, [0, 1], 250_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 165 MSPS, 2 channel", 0, [0, 1], 165_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 100 MSPS, 2 channel", 0, [0, 1], 100_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 250 MSPS, 3 channel", 0, [0, 1, 2], 250_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 165 MSPS, 3 channel", 0, [0, 1, 2], 165_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 100 MSPS, 3 channel", 0, [0, 1, 2], 100_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 250 MSPS, 4 channel", 0, [0, 1, 2, 3], 250_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 165 MSPS, 4 channel", 0, [0, 1, 2, 3], 165_000_000, Variables),
            new PgaLoadStep("Channel 1 - PGA loading scale - 100 MSPS, 4 channel", 0, [0, 1, 2, 3], 100_000_000, Variables),

            new Step("Disconnect signal generator"){ Action = (CancellationToken cancellationToken) => { SigGens.Instance.SetSdgChannel([]); return Sequencer.Status.Done; }},

            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L0", 1, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L1", 1, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L2", 1, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L3", 1, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L4", 1, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L5", 1, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L6", 1, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L7", 1, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L8", 1, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L9", 1, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L10", 1, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L0", 1, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L1", 1, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L2", 1, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L3", 1, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L4", 1, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L5", 1, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L6", 1, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L7", 1, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L8", 1, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L9", 1, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L10", 1, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L0", 1, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L1", 1, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L2", 1, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L3", 1, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L4", 1, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L5", 1, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L6", 1, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L7", 1, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L8", 1, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L9", 1, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L10", 1, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L0", 1, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L1", 1, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L2", 1, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L3", 1, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L4", 1, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L5", 1, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L6", 1, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L7", 1, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L8", 1, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L9", 1, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L10", 1, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new FindSigGenZeroStep("Channel 2 - Signal generator zero", 1, Variables),

            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L0", 1, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L1", 1, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L2", 1, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L3", 1, PgaPreampGain.High, pgaLadder: 3, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L4", 1, PgaPreampGain.High, pgaLadder: 4, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L5", 1, PgaPreampGain.High, pgaLadder: 5, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L6", 1, PgaPreampGain.High, pgaLadder: 6, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L7", 1, PgaPreampGain.High, pgaLadder: 7, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L8", 1, PgaPreampGain.High, pgaLadder: 8, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L9", 1, PgaPreampGain.High, pgaLadder: 9, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - HG L10", 1, PgaPreampGain.High, pgaLadder: 10, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L0", 1, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L1", 1, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L2", 1, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L3", 1, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L4", 1, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L5", 1, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L6", 1, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L7", 1, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L8", 1, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L9", 1, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new BufferInputVppStep("Channel 2 - Buffer input Vpp - LG L10", 1, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AttenuatorStep("Channel 2 - Attenuator scale", 1, Variables),

            new PgaLoadSetupStep("Channel 2 - Setup PGA loading scale", 1, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 660 MSPS, 1 channel", 1, [1], 660_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 500 MSPS, 1 channel", 1, [1], 500_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 330 MSPS, 1 channel", 1, [1], 330_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 250 MSPS, 1 channel", 1, [1], 250_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 165 MSPS, 1 channel", 1, [1], 165_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 100 MSPS, 1 channel", 1, [1], 100_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 500 MSPS, 2 channel", 1, [1, 2], 500_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 330 MSPS, 2 channel", 1, [1, 2], 330_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 250 MSPS, 2 channel", 1, [1, 2], 250_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 165 MSPS, 2 channel", 1, [1, 2], 165_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 100 MSPS, 2 channel", 1, [1, 2], 100_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 250 MSPS, 3 channel", 1, [1, 2, 3], 250_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 165 MSPS, 3 channel", 1, [1, 2, 3], 165_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 100 MSPS, 3 channel", 1, [1, 2, 3], 100_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 250 MSPS, 4 channel", 1, [0, 1, 2, 3], 250_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 165 MSPS, 4 channel", 1, [0, 1, 2, 3], 165_000_000, Variables),
            new PgaLoadStep("Channel 2 - PGA loading scale - 100 MSPS, 4 channel", 1, [0, 1, 2, 3], 100_000_000, Variables),

            new Step("Disconnect signal generator"){ Action = (CancellationToken cancellationToken) => { SigGens.Instance.SetSdgChannel([]); return Sequencer.Status.Done; }},

            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L0", 2, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L1", 2, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L2", 2, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L3", 2, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L4", 2, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L5", 2, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L6", 2, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L7", 2, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L8", 2, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L9", 2, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L10", 2, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L0", 2, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L1", 2, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L2", 2, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L3", 2, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L4", 2, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L5", 2, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L6", 2, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L7", 2, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L8", 2, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L9", 2, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L10", 2, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L0", 2, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L1", 2, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L2", 2, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L3", 2, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L4", 2, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L5", 2, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L6", 2, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L7", 2, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L8", 2, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L9", 2, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L10", 2, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L0", 2, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L1", 2, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L2", 2, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L3", 2, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L4", 2, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L5", 2, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L6", 2, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L7", 2, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L8", 2, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L9", 2, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L10", 2, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new FindSigGenZeroStep("Channel 3 - Signal generator zero", 2, Variables),

            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L0", 2, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L1", 2, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L2", 2, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L3", 2, PgaPreampGain.High, pgaLadder: 3, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L4", 2, PgaPreampGain.High, pgaLadder: 4, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L5", 2, PgaPreampGain.High, pgaLadder: 5, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L6", 2, PgaPreampGain.High, pgaLadder: 6, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L7", 2, PgaPreampGain.High, pgaLadder: 7, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L8", 2, PgaPreampGain.High, pgaLadder: 8, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L9", 2, PgaPreampGain.High, pgaLadder: 9, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - HG L10", 2, PgaPreampGain.High, pgaLadder: 10, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L0", 2, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L1", 2, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L2", 2, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L3", 2, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L4", 2, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L5", 2, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L6", 2, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L7", 2, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L8", 2, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L9", 2, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new BufferInputVppStep("Channel 3 - Buffer input Vpp - LG L10", 2, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AttenuatorStep("Channel 3 - Attenuator scale", 2, Variables),

            new PgaLoadSetupStep("Channel 3 - Setup PGA loading scale", 2, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 660 MSPS, 1 channel", 2, [2], 660_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 500 MSPS, 1 channel", 2, [2], 500_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 330 MSPS, 1 channel", 2, [2], 330_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 250 MSPS, 1 channel", 2, [2], 250_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 165 MSPS, 1 channel", 2, [2], 165_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 100 MSPS, 1 channel", 2, [2], 100_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 500 MSPS, 2 channel", 2, [2, 3], 500_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 330 MSPS, 2 channel", 2, [2, 3], 330_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 250 MSPS, 2 channel", 2, [2, 3], 250_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 165 MSPS, 2 channel", 2, [2, 3], 165_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 100 MSPS, 2 channel", 2, [2, 3], 100_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 250 MSPS, 3 channel", 2, [2, 3, 0], 250_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 165 MSPS, 3 channel", 2, [2, 3, 0], 165_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 100 MSPS, 3 channel", 2, [2, 3, 0], 100_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 250 MSPS, 4 channel", 2, [0, 1, 2, 3], 250_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 165 MSPS, 4 channel", 2, [0, 1, 2, 3], 165_000_000, Variables),
            new PgaLoadStep("Channel 3 - PGA loading scale - 100 MSPS, 4 channel", 2, [0, 1, 2, 3], 100_000_000, Variables),

            new Step("Disconnect signal generator"){ Action = (CancellationToken cancellationToken) => { SigGens.Instance.SetSdgChannel([]); return Sequencer.Status.Done; }},

            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L0", 3, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L1", 3, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L2", 3, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L3", 3, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L4", 3, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L5", 3, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L6", 3, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L7", 3, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L8", 3, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L9", 3, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L10", 3, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L0", 3, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L1", 3, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L2", 3, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L3", 3, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L4", 3, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L5", 3, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L6", 3, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L7", 3, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L8", 3, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L9", 3, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L10", 3, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L0", 3, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L1", 3, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L2", 3, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L3", 3, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L4", 3, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L5", 3, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L6", 3, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L7", 3, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L8", 3, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L9", 3, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L10", 3, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L0", 3, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L1", 3, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L2", 3, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L3", 3, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L4", 3, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L5", 3, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L6", 3, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L7", 3, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L8", 3, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L9", 3, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L10", 3, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new FindSigGenZeroStep("Channel 4 - Signal generator zero", 3, Variables),

            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L0", 3, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L1", 3, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L2", 3, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L3", 3, PgaPreampGain.High, pgaLadder: 3, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L4", 3, PgaPreampGain.High, pgaLadder: 4, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L5", 3, PgaPreampGain.High, pgaLadder: 5, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L6", 3, PgaPreampGain.High, pgaLadder: 6, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L7", 3, PgaPreampGain.High, pgaLadder: 7, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L8", 3, PgaPreampGain.High, pgaLadder: 8, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L9", 3, PgaPreampGain.High, pgaLadder: 9, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - HG L10", 3, PgaPreampGain.High, pgaLadder: 10, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L0", 3, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L1", 3, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L2", 3, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L3", 3, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L4", 3, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L5", 3, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L6", 3, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L7", 3, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L8", 3, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L9", 3, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new BufferInputVppStep("Channel 4 - Buffer input Vpp - LG L10", 3, PgaPreampGain.Low, pgaLadder: 10, Variables),
            new AttenuatorStep("Channel 4 - Attenuator scale", 3, Variables),

            new PgaLoadSetupStep("Channel 4 - Setup PGA loading scale", 3, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 660 MSPS, 1 channel", 3, [3], 660_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 500 MSPS, 1 channel", 3, [3], 500_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 330 MSPS, 1 channel", 3, [3], 330_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 250 MSPS, 1 channel", 3, [3], 250_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 165 MSPS, 1 channel", 3, [3], 165_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 100 MSPS, 1 channel", 3, [3], 100_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 500 MSPS, 2 channel", 3, [3, 0], 500_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 330 MSPS, 2 channel", 3, [3, 0], 330_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 250 MSPS, 2 channel", 3, [3, 0], 250_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 165 MSPS, 2 channel", 3, [3, 0], 165_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 100 MSPS, 2 channel", 3, [3, 0], 100_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 250 MSPS, 3 channel", 3, [3, 0, 1], 250_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 165 MSPS, 3 channel", 3, [3, 0, 1], 165_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 100 MSPS, 3 channel", 3, [3, 0, 1], 100_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 250 MSPS, 4 channel", 3, [0, 1, 2, 3], 250_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 165 MSPS, 4 channel", 3, [0, 1, 2, 3], 165_000_000, Variables),
            new PgaLoadStep("Channel 4 - PGA loading scale - 100 MSPS, 4 channel", 3, [0, 1, 2, 3], 100_000_000, Variables),

            new Step("Disconnect signal generator"){ Action = (CancellationToken cancellationToken) => { SigGens.Instance.SetSdgChannel([]); return Sequencer.Status.Done; }},

            new SaveUserCalToFileStep("Save calibration to file", Variables) { AllowSkip = true },
            new SaveUserCalToDeviceStep("Save calibration to device", Variables) { AllowSkip = true },

            new Step("Cleanup"){ Action = (CancellationToken cancellationToken) => {
                Instruments.Instance.Close();
                return Sequencer.Status.Done;
            }},
        ];
    }
}
