using TS.NET.Sequencer;

namespace TS.NET.Sequences;

public class SelfCalibrationSequence : Sequence
{
    public SelfCalibrationVariables Variables { get; private set; }

    public SelfCalibrationSequence(ModalUiContext modalUiContext, SelfCalibrationVariables variables)
    {
        Name = "Self calibration";
        Variables = variables;
        AddSteps(modalUiContext);
        SetStepIndices();
    }

    private void AddSteps(ModalUiContext modalUiContext)
    {
        Steps =
        [
            new ModalDialogStep("Cable check", modalUiContext)
            {
                Title = "Cable check",
                Message = "Are all cables disconnected from channels 1-4?",
                Buttons = DialogButtons.YesNo,
                Icon = DialogIcon.Question
            },
            new InitialiseDeviceStep("Initialise device", Variables),
            new LoadUserCalFromDeviceFallbackToFileStep("Load calibration from device/file", Variables),
            new WarmupStep("Warmup device", Variables) { Skip = false, AllowSkip = true },

            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L0", 0, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L1", 0, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L2", 0, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L3", 0, PgaPreampGain.High, 3, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L4", 0, PgaPreampGain.High, 4, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L5", 0, PgaPreampGain.High, 5, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L6", 0, PgaPreampGain.High, 6, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L7", 0, PgaPreampGain.High, 7, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L8", 0, PgaPreampGain.High, 8, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L9", 0, PgaPreampGain.High, 9, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - HG L10", 0, PgaPreampGain.High, 10, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L0", 0, PgaPreampGain.Low, 0, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L1", 0, PgaPreampGain.Low, 1, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L2", 0, PgaPreampGain.Low, 2, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L3", 0, PgaPreampGain.Low, 3, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L4", 0, PgaPreampGain.Low, 4, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L5", 0, PgaPreampGain.Low, 5, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L6", 0, PgaPreampGain.Low, 6, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L7", 0, PgaPreampGain.Low, 7, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L8", 0, PgaPreampGain.Low, 8, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L9", 0, PgaPreampGain.Low, 9, Variables),
            new TrimOffsetDacGainStep("Channel 1 - Trim offset DAC scale - LG L10", 0, PgaPreampGain.Low, 10, Variables),

            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L0", 0, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L1", 0, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L2", 0, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L3", 0, PgaPreampGain.High, 3, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L4", 0, PgaPreampGain.High, 4, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L5", 0, PgaPreampGain.High, 5, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L6", 0, PgaPreampGain.High, 6, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L7", 0, PgaPreampGain.High, 7, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L8", 0, PgaPreampGain.High, 8, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L9", 0, PgaPreampGain.High, 9, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - HG L10", 0, PgaPreampGain.High, 10, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L0", 0, PgaPreampGain.Low, 0, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L1", 0, PgaPreampGain.Low, 1, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L2", 0, PgaPreampGain.Low, 2, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L3", 0, PgaPreampGain.Low, 3, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L4", 0, PgaPreampGain.Low, 4, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L5", 0, PgaPreampGain.Low, 5, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L6", 0, PgaPreampGain.Low, 6, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L7", 0, PgaPreampGain.Low, 7, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L8", 0, PgaPreampGain.Low, 8, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L9", 0, PgaPreampGain.Low, 9, Variables),
            new TrimOffsetDacZeroStep("Channel 1 - Trim offset DAC zero - LG L10", 0, PgaPreampGain.Low, 10, Variables),

            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L0", 1, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L1", 1, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L2", 1, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L3", 1, PgaPreampGain.High, 3, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L4", 1, PgaPreampGain.High, 4, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L5", 1, PgaPreampGain.High, 5, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L6", 1, PgaPreampGain.High, 6, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L7", 1, PgaPreampGain.High, 7, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L8", 1, PgaPreampGain.High, 8, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L9", 1, PgaPreampGain.High, 9, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - HG L10", 1, PgaPreampGain.High, 10, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L0", 1, PgaPreampGain.Low, 0, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L1", 1, PgaPreampGain.Low, 1, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L2", 1, PgaPreampGain.Low, 2, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L3", 1, PgaPreampGain.Low, 3, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L4", 1, PgaPreampGain.Low, 4, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L5", 1, PgaPreampGain.Low, 5, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L6", 1, PgaPreampGain.Low, 6, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L7", 1, PgaPreampGain.Low, 7, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L8", 1, PgaPreampGain.Low, 8, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L9", 1, PgaPreampGain.Low, 9, Variables),
            new TrimOffsetDacGainStep("Channel 2 - Trim offset DAC scale - LG L10", 1, PgaPreampGain.Low, 10, Variables),

            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L0", 1, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L1", 1, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L2", 1, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L3", 1, PgaPreampGain.High, 3, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L4", 1, PgaPreampGain.High, 4, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L5", 1, PgaPreampGain.High, 5, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L6", 1, PgaPreampGain.High, 6, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L7", 1, PgaPreampGain.High, 7, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L8", 1, PgaPreampGain.High, 8, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L9", 1, PgaPreampGain.High, 9, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - HG L10", 1, PgaPreampGain.High, 10, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L0", 1, PgaPreampGain.Low, 0, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L1", 1, PgaPreampGain.Low, 1, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L2", 1, PgaPreampGain.Low, 2, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L3", 1, PgaPreampGain.Low, 3, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L4", 1, PgaPreampGain.Low, 4, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L5", 1, PgaPreampGain.Low, 5, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L6", 1, PgaPreampGain.Low, 6, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L7", 1, PgaPreampGain.Low, 7, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L8", 1, PgaPreampGain.Low, 8, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L9", 1, PgaPreampGain.Low, 9, Variables),
            new TrimOffsetDacZeroStep("Channel 2 - Trim offset DAC zero - LG L10", 1, PgaPreampGain.Low, 10, Variables),

            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L0", 2, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L1", 2, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L2", 2, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L3", 2, PgaPreampGain.High, 3, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L4", 2, PgaPreampGain.High, 4, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L5", 2, PgaPreampGain.High, 5, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L6", 2, PgaPreampGain.High, 6, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L7", 2, PgaPreampGain.High, 7, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L8", 2, PgaPreampGain.High, 8, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L9", 2, PgaPreampGain.High, 9, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - HG L10", 2, PgaPreampGain.High, 10, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L0", 2, PgaPreampGain.Low, 0, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L1", 2, PgaPreampGain.Low, 1, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L2", 2, PgaPreampGain.Low, 2, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L3", 2, PgaPreampGain.Low, 3, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L4", 2, PgaPreampGain.Low, 4, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L5", 2, PgaPreampGain.Low, 5, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L6", 2, PgaPreampGain.Low, 6, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L7", 2, PgaPreampGain.Low, 7, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L8", 2, PgaPreampGain.Low, 8, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L9", 2, PgaPreampGain.Low, 9, Variables),
            new TrimOffsetDacGainStep("Channel 3 - Trim offset DAC scale - LG L10", 2, PgaPreampGain.Low, 10, Variables),

            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L0", 2, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L1", 2, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L2", 2, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L3", 2, PgaPreampGain.High, 3, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L4", 2, PgaPreampGain.High, 4, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L5", 2, PgaPreampGain.High, 5, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L6", 2, PgaPreampGain.High, 6, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L7", 2, PgaPreampGain.High, 7, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L8", 2, PgaPreampGain.High, 8, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L9", 2, PgaPreampGain.High, 9, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - HG L10", 2, PgaPreampGain.High, 10, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L0", 2, PgaPreampGain.Low, 0, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L1", 2, PgaPreampGain.Low, 1, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L2", 2, PgaPreampGain.Low, 2, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L3", 2, PgaPreampGain.Low, 3, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L4", 2, PgaPreampGain.Low, 4, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L5", 2, PgaPreampGain.Low, 5, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L6", 2, PgaPreampGain.Low, 6, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L7", 2, PgaPreampGain.Low, 7, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L8", 2, PgaPreampGain.Low, 8, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L9", 2, PgaPreampGain.Low, 9, Variables),
            new TrimOffsetDacZeroStep("Channel 3 - Trim offset DAC zero - LG L10", 2, PgaPreampGain.Low, 10, Variables),

            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L0", 3, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L1", 3, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L2", 3, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L3", 3, PgaPreampGain.High, 3, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L4", 3, PgaPreampGain.High, 4, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L5", 3, PgaPreampGain.High, 5, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L6", 3, PgaPreampGain.High, 6, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L7", 3, PgaPreampGain.High, 7, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L8", 3, PgaPreampGain.High, 8, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L9", 3, PgaPreampGain.High, 9, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - HG L10", 3, PgaPreampGain.High, 10, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L0", 3, PgaPreampGain.Low, 0, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L1", 3, PgaPreampGain.Low, 1, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L2", 3, PgaPreampGain.Low, 2, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L3", 3, PgaPreampGain.Low, 3, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L4", 3, PgaPreampGain.Low, 4, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L5", 3, PgaPreampGain.Low, 5, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L6", 3, PgaPreampGain.Low, 6, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L7", 3, PgaPreampGain.Low, 7, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L8", 3, PgaPreampGain.Low, 8, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L9", 3, PgaPreampGain.Low, 9, Variables),
            new TrimOffsetDacGainStep("Channel 4 - Trim offset DAC scale - LG L10", 3, PgaPreampGain.Low, 10, Variables),

            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L0", 3, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L1", 3, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L2", 3, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(30), MaxRetries = 3 },
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L3", 3, PgaPreampGain.High, 3, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L4", 3, PgaPreampGain.High, 4, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L5", 3, PgaPreampGain.High, 5, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L6", 3, PgaPreampGain.High, 6, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L7", 3, PgaPreampGain.High, 7, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L8", 3, PgaPreampGain.High, 8, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L9", 3, PgaPreampGain.High, 9, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - HG L10", 3, PgaPreampGain.High, 10, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L0", 3, PgaPreampGain.Low, 0, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L1", 3, PgaPreampGain.Low, 1, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L2", 3, PgaPreampGain.Low, 2, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L3", 3, PgaPreampGain.Low, 3, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L4", 3, PgaPreampGain.Low, 4, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L5", 3, PgaPreampGain.Low, 5, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L6", 3, PgaPreampGain.Low, 6, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L7", 3, PgaPreampGain.Low, 7, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L8", 3, PgaPreampGain.Low, 8, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L9", 3, PgaPreampGain.Low, 9, Variables),
            new TrimOffsetDacZeroStep("Channel 4 - Trim offset DAC zero - LG L10", 3, PgaPreampGain.Low, 10, Variables),

            new SaveUserCalToFileStep("Save calibration to file", Variables) { AllowSkip = true },
            new SaveUserCalToDeviceStep("Save calibration to device", Variables) { AllowSkip = true },

            new Step("Cleanup"){ Action = (CancellationToken cancellationToken) => {
                Instruments.Instance.Close();
                return Sequencer.Status.Done;
            }},
        ];
    }
}
