using TS.NET.Sequencer;

namespace TS.NET.Sequences;

public class SelfCalibrationSequence : Sequence
{
    public SelfCalibrationVariables Variables { get; private set; }

    public SelfCalibrationSequence(ModalUiContext modalUiContext, SelfCalibrationVariables variables)
    {
        Name = "Self calibration";
        Variables = variables;
        AddSteps(modalUiContext);
        SetStepIndices();
    }

    private void AddSteps(ModalUiContext modalUiContext)
    {
        Steps =
        [
            new ModalDialogStep("Cable check", modalUiContext)
            {
                Title = "Cable check",
                Message = "Are all cables disconnected from channels 1-4?",
                Buttons = DialogButtons.YesNo,
                Icon = DialogIcon.Question
            },
            new InitialiseDeviceStep("Initialise device", Variables),
            new LoadCalibrationFromUserCalStep("Load calibration from device", Variables),
            new TemperatureCheckStep("Temperature check", Variables),

            new WarmupStep("Initial warmup", Variables, 2 * 60) { Skip = false, AllowSkip = true },
#region TrimDacZeroCold
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L0", 0, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L1", 0, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L2", 0, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L3", 0, PgaPreampGain.High, 3, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L4", 0, PgaPreampGain.High, 4, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L5", 0, PgaPreampGain.High, 5, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L6", 0, PgaPreampGain.High, 6, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L7", 0, PgaPreampGain.High, 7, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L8", 0, PgaPreampGain.High, 8, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L9", 0, PgaPreampGain.High, 9, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - HG L10", 0, PgaPreampGain.High, 10, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L0", 0, PgaPreampGain.Low, 0, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L1", 0, PgaPreampGain.Low, 1, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L2", 0, PgaPreampGain.Low, 2, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L3", 0, PgaPreampGain.Low, 3, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L4", 0, PgaPreampGain.Low, 4, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L5", 0, PgaPreampGain.Low, 5, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L6", 0, PgaPreampGain.Low, 6, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L7", 0, PgaPreampGain.Low, 7, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L8", 0, PgaPreampGain.Low, 8, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L9", 0, PgaPreampGain.Low, 9, Variables),
            new TrimDacZeroColdStep("Channel 1 - Trim DAC zero - Cold - LG L10", 0, PgaPreampGain.Low, 10, Variables) { PostAction = cancellationToken => { Variables.LastDacValue = 2048; } },

            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L0", 1, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L1", 1, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L2", 1, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L3", 1, PgaPreampGain.High, 3, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L4", 1, PgaPreampGain.High, 4, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L5", 1, PgaPreampGain.High, 5, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L6", 1, PgaPreampGain.High, 6, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L7", 1, PgaPreampGain.High, 7, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L8", 1, PgaPreampGain.High, 8, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L9", 1, PgaPreampGain.High, 9, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - HG L10", 1, PgaPreampGain.High, 10, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L0", 1, PgaPreampGain.Low, 0, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L1", 1, PgaPreampGain.Low, 1, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L2", 1, PgaPreampGain.Low, 2, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L3", 1, PgaPreampGain.Low, 3, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L4", 1, PgaPreampGain.Low, 4, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L5", 1, PgaPreampGain.Low, 5, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L6", 1, PgaPreampGain.Low, 6, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L7", 1, PgaPreampGain.Low, 7, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L8", 1, PgaPreampGain.Low, 8, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L9", 1, PgaPreampGain.Low, 9, Variables),
            new TrimDacZeroColdStep("Channel 2 - Trim DAC zero - Cold - LG L10", 1, PgaPreampGain.Low, 10, Variables) { PostAction = cancellationToken => { Variables.LastDacValue = 2048; } },

            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L0", 2, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L1", 2, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L2", 2, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L3", 2, PgaPreampGain.High, 3, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L4", 2, PgaPreampGain.High, 4, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L5", 2, PgaPreampGain.High, 5, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L6", 2, PgaPreampGain.High, 6, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L7", 2, PgaPreampGain.High, 7, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L8", 2, PgaPreampGain.High, 8, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L9", 2, PgaPreampGain.High, 9, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - HG L10", 2, PgaPreampGain.High, 10, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L0", 2, PgaPreampGain.Low, 0, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L1", 2, PgaPreampGain.Low, 1, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L2", 2, PgaPreampGain.Low, 2, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L3", 2, PgaPreampGain.Low, 3, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L4", 2, PgaPreampGain.Low, 4, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L5", 2, PgaPreampGain.Low, 5, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L6", 2, PgaPreampGain.Low, 6, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L7", 2, PgaPreampGain.Low, 7, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L8", 2, PgaPreampGain.Low, 8, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L9", 2, PgaPreampGain.Low, 9, Variables),
            new TrimDacZeroColdStep("Channel 3 - Trim DAC zero - Cold - LG L10", 2, PgaPreampGain.Low, 10, Variables) { PostAction = cancellationToken => { Variables.LastDacValue = 2048; } },

            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L0", 3, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L1", 3, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L2", 3, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L3", 3, PgaPreampGain.High, 3, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L4", 3, PgaPreampGain.High, 4, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L5", 3, PgaPreampGain.High, 5, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L6", 3, PgaPreampGain.High, 6, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L7", 3, PgaPreampGain.High, 7, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L8", 3, PgaPreampGain.High, 8, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L9", 3, PgaPreampGain.High, 9, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - HG L10", 3, PgaPreampGain.High, 10, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L0", 3, PgaPreampGain.Low, 0, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L1", 3, PgaPreampGain.Low, 1, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L2", 3, PgaPreampGain.Low, 2, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L3", 3, PgaPreampGain.Low, 3, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L4", 3, PgaPreampGain.Low, 4, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L5", 3, PgaPreampGain.Low, 5, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L6", 3, PgaPreampGain.Low, 6, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L7", 3, PgaPreampGain.Low, 7, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L8", 3, PgaPreampGain.Low, 8, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L9", 3, PgaPreampGain.Low, 9, Variables),
            new TrimDacZeroColdStep("Channel 4 - Trim DAC zero - Cold - LG L10", 3, PgaPreampGain.Low, 10, Variables) { PostAction = cancellationToken => { Variables.LastDacValue = 2048; } },
#endregion
            new WarmupStep("Full warmup", Variables, 40 * 60) { Skip = false, AllowSkip = true },
#region TrimDacZeroHot
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L0", 0, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L1", 0, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L2", 0, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L3", 0, PgaPreampGain.High, 3, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L4", 0, PgaPreampGain.High, 4, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L5", 0, PgaPreampGain.High, 5, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L6", 0, PgaPreampGain.High, 6, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L7", 0, PgaPreampGain.High, 7, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L8", 0, PgaPreampGain.High, 8, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L9", 0, PgaPreampGain.High, 9, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - HG L10", 0, PgaPreampGain.High, 10, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L0", 0, PgaPreampGain.Low, 0, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L1", 0, PgaPreampGain.Low, 1, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L2", 0, PgaPreampGain.Low, 2, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L3", 0, PgaPreampGain.Low, 3, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L4", 0, PgaPreampGain.Low, 4, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L5", 0, PgaPreampGain.Low, 5, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L6", 0, PgaPreampGain.Low, 6, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L7", 0, PgaPreampGain.Low, 7, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L8", 0, PgaPreampGain.Low, 8, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L9", 0, PgaPreampGain.Low, 9, Variables),
            new TrimDacZeroHotStep("Channel 1 - Trim DAC zero - Hot - LG L10", 0, PgaPreampGain.Low, 10, Variables) { PostAction = cancellationToken => { Variables.LastDacValue = 2048; } },

            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L0", 1, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L1", 1, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L2", 1, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L3", 1, PgaPreampGain.High, 3, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L4", 1, PgaPreampGain.High, 4, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L5", 1, PgaPreampGain.High, 5, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L6", 1, PgaPreampGain.High, 6, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L7", 1, PgaPreampGain.High, 7, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L8", 1, PgaPreampGain.High, 8, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L9", 1, PgaPreampGain.High, 9, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - HG L10", 1, PgaPreampGain.High, 10, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L0", 1, PgaPreampGain.Low, 0, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L1", 1, PgaPreampGain.Low, 1, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L2", 1, PgaPreampGain.Low, 2, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L3", 1, PgaPreampGain.Low, 3, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L4", 1, PgaPreampGain.Low, 4, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L5", 1, PgaPreampGain.Low, 5, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L6", 1, PgaPreampGain.Low, 6, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L7", 1, PgaPreampGain.Low, 7, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L8", 1, PgaPreampGain.Low, 8, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L9", 1, PgaPreampGain.Low, 9, Variables),
            new TrimDacZeroHotStep("Channel 2 - Trim DAC zero - Hot - LG L10", 1, PgaPreampGain.Low, 10, Variables){ PostAction = cancellationToken => { Variables.LastDacValue = 2048; } },

            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L0", 2, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L1", 2, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L2", 2, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L3", 2, PgaPreampGain.High, 3, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L4", 2, PgaPreampGain.High, 4, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L5", 2, PgaPreampGain.High, 5, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L6", 2, PgaPreampGain.High, 6, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L7", 2, PgaPreampGain.High, 7, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L8", 2, PgaPreampGain.High, 8, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L9", 2, PgaPreampGain.High, 9, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - HG L10", 2, PgaPreampGain.High, 10, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L0", 2, PgaPreampGain.Low, 0, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L1", 2, PgaPreampGain.Low, 1, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L2", 2, PgaPreampGain.Low, 2, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L3", 2, PgaPreampGain.Low, 3, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L4", 2, PgaPreampGain.Low, 4, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L5", 2, PgaPreampGain.Low, 5, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L6", 2, PgaPreampGain.Low, 6, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L7", 2, PgaPreampGain.Low, 7, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L8", 2, PgaPreampGain.Low, 8, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L9", 2, PgaPreampGain.Low, 9, Variables),
            new TrimDacZeroHotStep("Channel 3 - Trim DAC zero - Hot - LG L10", 2, PgaPreampGain.Low, 10, Variables){ PostAction = cancellationToken => { Variables.LastDacValue = 2048; } },

            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L0", 3, PgaPreampGain.High, 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L1", 3, PgaPreampGain.High, 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L2", 3, PgaPreampGain.High, 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L3", 3, PgaPreampGain.High, 3, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L4", 3, PgaPreampGain.High, 4, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L5", 3, PgaPreampGain.High, 5, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L6", 3, PgaPreampGain.High, 6, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L7", 3, PgaPreampGain.High, 7, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L8", 3, PgaPreampGain.High, 8, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L9", 3, PgaPreampGain.High, 9, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - HG L10", 3, PgaPreampGain.High, 10, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L0", 3, PgaPreampGain.Low, 0, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L1", 3, PgaPreampGain.Low, 1, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L2", 3, PgaPreampGain.Low, 2, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L3", 3, PgaPreampGain.Low, 3, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L4", 3, PgaPreampGain.Low, 4, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L5", 3, PgaPreampGain.Low, 5, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L6", 3, PgaPreampGain.Low, 6, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L7", 3, PgaPreampGain.Low, 7, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L8", 3, PgaPreampGain.Low, 8, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L9", 3, PgaPreampGain.Low, 9, Variables),
            new TrimDacZeroHotStep("Channel 4 - Trim DAC zero - Hot - LG L10", 3, PgaPreampGain.Low, 10, Variables) { PostAction = cancellationToken => { Variables.LastDacValue = 2048; Variables.TrimDacZeroCalibrated = true; } },
            #endregion
#region TrimDacScale
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L0", 0, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L1", 0, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L2", 0, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L3", 0, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L4", 0, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L5", 0, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L6", 0, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L7", 0, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L8", 0, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L9", 0, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - HG L10", 0, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L0", 0, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L1", 0, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L2", 0, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L3", 0, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L4", 0, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L5", 0, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L6", 0, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L7", 0, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L8", 0, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L9", 0, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimDacScaleStep("Channel 1 - Trim DAC scale - LG L10", 0, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L0", 1, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L1", 1, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L2", 1, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L3", 1, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L4", 1, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L5", 1, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L6", 1, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L7", 1, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L8", 1, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L9", 1, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - HG L10", 1, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L0", 1, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L1", 1, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L2", 1, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L3", 1, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L4", 1, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L5", 1, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L6", 1, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L7", 1, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L8", 1, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L9", 1, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimDacScaleStep("Channel 2 - Trim DAC scale - LG L10", 1, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L0", 2, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L1", 2, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L2", 2, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L3", 2, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L4", 2, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L5", 2, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L6", 2, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L7", 2, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L8", 2, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L9", 2, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - HG L10", 2, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L0", 2, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L1", 2, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L2", 2, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L3", 2, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L4", 2, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L5", 2, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L6", 2, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L7", 2, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L8", 2, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L9", 2, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimDacScaleStep("Channel 3 - Trim DAC scale - LG L10", 2, PgaPreampGain.Low, pgaLadder: 10, Variables),

            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L0", 3, PgaPreampGain.High, pgaLadder: 0, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L1", 3, PgaPreampGain.High, pgaLadder: 1, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L2", 3, PgaPreampGain.High, pgaLadder: 2, Variables) { IgnoreError = true, Timeout = TimeSpan.FromSeconds(60), MaxRetries = 2 },
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L3", 3, PgaPreampGain.High, pgaLadder: 3, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L4", 3, PgaPreampGain.High, pgaLadder: 4, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L5", 3, PgaPreampGain.High, pgaLadder: 5, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L6", 3, PgaPreampGain.High, pgaLadder: 6, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L7", 3, PgaPreampGain.High, pgaLadder: 7, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L8", 3, PgaPreampGain.High, pgaLadder: 8, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L9", 3, PgaPreampGain.High, pgaLadder: 9, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - HG L10", 3, PgaPreampGain.High, pgaLadder: 10, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L0", 3, PgaPreampGain.Low, pgaLadder: 0, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L1", 3, PgaPreampGain.Low, pgaLadder: 1, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L2", 3, PgaPreampGain.Low, pgaLadder: 2, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L3", 3, PgaPreampGain.Low, pgaLadder: 3, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L4", 3, PgaPreampGain.Low, pgaLadder: 4, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L5", 3, PgaPreampGain.Low, pgaLadder: 5, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L6", 3, PgaPreampGain.Low, pgaLadder: 6, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L7", 3, PgaPreampGain.Low, pgaLadder: 7, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L8", 3, PgaPreampGain.Low, pgaLadder: 8, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L9", 3, PgaPreampGain.Low, pgaLadder: 9, Variables),
            new TrimDacScaleStep("Channel 4 - Trim DAC scale - LG L10", 3, PgaPreampGain.Low, pgaLadder: 10, Variables) { PostAction = cancellationToken => { Variables.TrimDacScaleCalibrated = true; } },
#endregion
            new Step("Update calibration"){ Action = (CancellationToken cancellationToken) => {
                Variables.Calibration.Serial = Variables.HwidSerial;
                Variables.CalibrationTimestamp = DateTimeOffset.UtcNow;
                Variables.Calibration.Timestamp = Variables.CalibrationTimestamp.ToString("yyyy-MM-ddTHH:mm:ssZ");
                return Sequencer.Status.Done;
            }},
            new SaveUserCalToFileStep("Save calibration to file", Variables) { AllowSkip = true },
            new SaveUserCalToDeviceStep("Save calibration to device", Variables) { AllowSkip = true },

            new Step("Cleanup"){ Action = (CancellationToken cancellationToken) => {
                Instruments.Instance.Close();
                return Sequencer.Status.Done;
            }},
        ];
    }
}
