name: Build & test
on: [push]
jobs:
  build:   
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./source
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./source
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./source
      - name:  Run build scripts
        working-directory: ./build-scripts
        run:   |
               if [ "$RUNNER_OS" == "Linux" ]; then
                    ./"TS.NET.Engine (linux-x64).bash"
               elif [ "$RUNNER_OS" == "Windows" ]; then
                    powershell -ExecutionPolicy Bypass -File "TS.NET.Engine (win-x64).ps1"
               else
                    echo "$RUNNER_OS not supported"
                    exit 1
               fi
        shell: bash